FROM mongo:6.0

# Set environment variables for default credentials
ENV MONGO_INITDB_ROOT_USERNAME=client
ENV MONGO_INITDB_ROOT_PASSWORD=root
ENV MONGO_INITDB_DATABASE=app

# Expose MongoDB default port
EXPOSE 27017